### ISSUE TITLE
Congress.gov Public Forum API Presentations

### ISSUE THREAD

**Issue by rbram** [LibraryOfCongress/api.congress.gov#271]
Hello. On 9/18, at 1pm, the Library is going to hold a Congress.gov Public Forum. You can participate online or in-person. This Forum will provide an update on the latest Congress.gov enhancements and it will also be a listening session where the Library and our data partners can learn how we can better serve your legislative information needs.
One of the items we will discuss is the Congress.gov API. As part of that discussion, we are interested in having users discuss their unique applications that have incorporated data from the Congress.gov API. If you would be interested in providing a two-minute presentation, would you please let us know by responding to this issue?
You can learn more about the Forum here: https://blogs.loc.gov/law/2024/08/join-us-for-a-congress-gov-public-forum-on-september-18th/

**Comment by stephbuon** [comment]
From what I can see, the Congress API only provides records in PDF format, which is very difficult for quantitative analysis because the data is unstructured. 

To work with the data, a structured format--like CSV or JSON--with columns for details such as name, title, and date is needed. 

In the past, users have been able to obtain structured data by scrapping the websites HTML, which contains tags that separate these details. However, when I have tried to scrape the data I am immediately banned. 

Can you please answer: How can I access to a structured version of the data? Is it at all possible to get JSON or HTML versions of the Congressional records so that I can use them in analysis?

**Comment by apreiter18** [comment]
> From what I can see, the Congress API only provides records in PDF format, which is very difficult for quantitative analysis because the data is unstructured.
> 
> To work with the data, a structured format--like CSV or JSON--that delineates details such as name, title, and date is needed.
> 
> In the past, users have been able to obtain structured data by scrapping the websites HTML, which contains tags that separate these details. However, when I have tried to scrape the data I am immediately banned.
> 
> Can you please answer: How can I access to a structured version of the data? Is it at all possible to get JSON or HTML versions of the Congressional records so that I can use them in analysis?
> 
> Thank you in advance for your response.

related to issue #273
