### ISSUE TITLE
Improve member photo quality

### ISSUE THREAD

**Issue by lukefretwell** [LibraryOfCongress/api.congress.gov#53]
Member photos seem to be of inconsistent quality. Would be great to have access to larger sizes.

**Comment by rbram** [comment]
Thanks for your feedback. Member photos are of inconsistent quality because they are aggregated from different data sources (some are from the Biographical Directory and others are from GPO’s Member Guide). We recommend that you use the thumbnail size which is the size that Congress.gov uses. Thank you for pointing out this irregularity, we will account for it in the User Guide.

**Comment by lukefretwell** [comment]
Thank you. Any reason why you wouldn't host these yourself?

Here's what they look like in how we're displaying:

https://govfresh.com/thoughts/civic-hacking-library-of-congress-part-1

They look fine but would be great to have easy access to better quality images.
