### ISSUE TITLE
RATE LIMIT

### ISSUE THREAD

**Issue by vacorda** [LibraryOfCongress/api.congress.gov#55]
May I know what are the exact rules for RATE LIMIT.
I read https://github.com/LibraryOfCongress/api.congress.gov/issues/35 but it is a bit vague.

I keep hitting it even after just a dozen queries. This is even after a day of not doing anything.
Thanks again

**Comment by BhinbahadurUK** [comment]
Open release
Set box types open query
Nominate types of boxes
Formats are most important for extract precon transform
Nominate afofile or key roots finer tuning now

UK Bhinbahadur

**Comment by mnewatloc** [comment]
It is odd that you're hitting the rate limit with that level of use. Can you share what your queries are?

**Comment by savage345906** [comment]
yes all of my bank accounts have been shut down my clients have been also
taken advantage of of money and this person is just constantly trying to
access and hack my phone or any device I've probably purchased seven phones
now also a Verizon tech spent 20 hours with me watching this person being
able to hack. This person does a lot of git hub and other software. I
believe that she is a private detective of some sort because I was able to
see her searches at one point when she had taken over my email addresses
and my iCloud account. She was logging into homeland security and private
detective websites. she is also taking over my business Facebook page
because I no longer have access to my email or my website she was also
making money off of pictures and signing up for credit cards and loans etc.
but I do believe that she has government access of some sort. please advise
dawn miller

**Comment by ryparker** [comment]
It would be nice to have some guidance that helps users avoid the rate limit.

Suggestions:

- Return a [`Retry-After` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After).
- Disclose the recommended delay between requests or ideal requests per hour.


I'm getting 429 responses even with a 1-3 second delay between requests. I also handle the 429 response by retrying up to 10 times with an exponential backoff delay ([according to Google's recommendations](https://cloud.google.com/storage/docs/retry-strategy#exponential-backoff)). I usually get a successful response after 4-8 retries.

My query pattern goes something like this:
- Fetch 250 bills from the list API
- For each bill in list fetch from the following APIs:
	- details
	- actions
	- cosponsors
	- committees
	- summaries
	- subjects
	- titles
	- related bills
	- amendments
	- texts

I start to see the server return 429 after about 1000 requests/hour.

**Comment by ryparker** [comment]
It looks like there's now a few headers on the request to help with the rate limit problem:

all response headers:
- `X-Ratelimit-Limit`: 1000
- `X-Ratelimit-Remaining`: Remaining requests before reset. 

429 response headers:
- `Retry-After`: seconds

> See [okta docs on rate limit headers](https://developer.okta.com/docs/reference/rl-best-practices/#check-your-rate-limits-with-okta-s-rate-limit-headers).

Would be nice to have the `X-Ratelimit-Reset` header though.

**Comment by ryparker** [comment]
One thing for the dev team to note is that the 429 response has a bad contact link:

```json
{
  "error": {
    "code": "OVER_RATE_LIMIT",
    "message": "You have exceeded your rate limit. Try again later or contact us at https://api.congress.gov:443/contact/ for assistance"
  }
}
```

**Comment by mnewatloc** [comment]
We will address the bad contact link. Thank you for bringing this to our attention.

**Comment by lhridley** [comment]
When you're updating the documentation can you please add documentation on sample headers when the rate limit is hit?  I'm writing a client to consume API data here, and knowing what headers to expect without having to write a script that makes requests until the rate limit is exceeded would be awesome!

Thanks in advance!
