### ISSUE TITLE
<textVersions> container missing in recent data

### ISSUE THREAD

**Issue by rhurst6** [LibraryOfCongress/api.congress.gov#67]
Noticed today that the textVersions container is missing in recent posts to the bulk depository.

It is present in 
https://www.govinfo.gov/bulkdata/BILLSTATUS/117/sres/BILLSTATUS-117sres719.xml

but missing in 
https://www.govinfo.gov/bulkdata/BILLSTATUS/118/sres/BILLSTATUS-118sres9.xml

can this be restored?

**Comment by jonquandt** [comment]
Good morning @rhurst6  -- it appears that the `textVersions` container is now available for the second bill in the BILLSTATUS

This probably occurred because there can be times when a BILLSTATUS exists, but the text has not yet been published on GovInfo. This is more likely to occur during the beginning of a Congress, when there are a large number of bills being resubmitted.

There does seem to be an empty item in the `textVersions` still, but that appears to be coming from the congress.gov API as well.
https://api.congress.gov/v3/bill/118/sres/8/text?format=json&api_key=DEMO_KEY 

That may be a question for the Congress.gov team. 

I hope this helps
